pr:
  autoCancel: true

jobs:

- job: 'Linux'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:
  - bash: echo "##vso[task.prependpath]/usr/share/miniconda/bin"
    displayName: Add conda to PATH
  - template: .azure-pipelines/test-template.yml

#Fails frequently due to CI issues
#- job: 'OSX'
#  pool:
#    vmImage: 'macOS-10.14'
#  strategy:
#    matrix:
#      Python37:
#        python.version: '3.7'
#    maxParallel: 1
#
#  steps:
#  - bash: echo "##vso[task.prependpath]$CONDA/bin"
#    displayName: Add conda to PATH
#  - template: .azure-pipelines/test-template.yml

- job: 'galaxy'
  dependsOn: 'Linux'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      batch1:
        python.version: '3.7'
        TESTGALAXY: '1'
      batch2:
        python.version: '3.7'
        TESTGALAXY: '2'
      batch3:
        python.version: '3.7'
        TESTGALAXY: '3'

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH
  - bash: conda create -n foo -q --yes -c conda-forge -c bioconda python=$(python.version) numpy scipy matplotlib==3.1.1 nose flake8 plotly pysam pyBigWig py2bit deeptoolsintervals planemo samtools
    displayName: Installing dependencies
  - bash: |
      source activate foo
      python setup.py install
    displayName: Installing deepTools
  - script: |
      source activate foo
      ./.planemo.sh $TESTGALAXY
    displayName: Run planemo
