name: pypi

on:
  create:
    tags:

defaults:
  run:
    shell: bash -l {0}

jobs:
  pypi:
    name: upload to pypi
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: mamba-org/setup-micromamba@main
      with:
        environment-file: .github/test_and_build.yml
        cache-downloads: true
        environment-name: test_and_build
    - name: build
      run: |
        micromamba activate test_and_build
        rm -f dist/*
        python -m build
    - name: upload
      env:
        TWINE_USERNAME: "__token__"
        TWINE_PASSWORD: ${{ secrets.pypi_password }}
      run: |
        micromamba activate test_and_build
        twine upload dist/*
